services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=ib_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ib_db
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

